### ISSUE TITLE
Get this app working in an LTS node version

### ISSUE THREAD

**Issue by camallen** [zooniverse/sugar#61]
related to #59 & #60 - the app works in node 11 currently.

On index request to setup the client the app crashes with the following stack trace.
```
GET / 304 2.029 ms - -
GET /primus.js 304 4.991 ms - -
GET /client.js 304 1.403 ms - -
(node:7) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
/node_app/node_modules/newrelic/lib/transaction/tracer/index.js:201
      throw err // Re-throwing application error, this is not an agent error.
      ^

TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptor (<anonymous>:null:null)
    at setHeader (/node_app/node_modules/access-control/node_modules/setheader/index.js:50:26)
    at Primus.control (/node_app/node_modules/access-control/index.js:125:7)
    at iterate (/node_app/node_modules/primus/transformer.js:136:14)
    at iterate (/node_app/node_modules/primus/transformer.js:132:14)
    at child.forEach (/node_app/node_modules/primus/transformer.js:141:4)
    at child.request (/node_app/node_modules/primus/transformer.js:178:8)
    at Server.emit (events.js:315:20)
    at Server.wrapped (/node_app/node_modules/newrelic/lib/transaction/tracer/index.js:193:22)
    at Server.wrappedHandler (/node_app/node_modules/newrelic/lib/instrumentation/core/http.js:219:47)
    at Server.wrapped (/node_app/node_modules/newrelic/lib/transaction/tracer/index.js:193:22)
    at Server.wrapTransactionInvocation (/node_app/node_modules/newrelic/lib/transaction/tracer/index.js:117:8)
    at Server.wrappedEmit [as emit] (/node_app/node_modules/newrelic/lib/instrumentation/core/http.js:512:28)
    at parserOnIncoming (_http_server.js:790:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
```

**Comment by camallen** [comment]
this work has been completed
